#!/bin/sh
#
# A script to create a git-version.json before the commit is pushed and deployed via GitHub Actions.
#

branch=$(git branch | grep '*' | sed 's/* //')
commitMessage=$(cat "${1:?Missing commit message file}")

# Cannot get the SHA because the SHA value will change depending
# on the changeset. So just have to use the commit message.

#shortSHA=$(git rev-parse --short branch)
#SHA=$(git rev-parse --short branch)

node ./src/git-version.js $branch "$commitMessage"

git add ./src/assets/git-version.json
git commit --amend --no-verify

echo "[Commit-msg] Added git-version.json for \"$commitMessage\""
