#!/bin/sh
#
# A script to create a git-version.json before the commit is pushed and deployed via GitHub Actions.
#

#IS_AMEND=$(ps -ocommand= -p $PPID | grep -e '--amend');
#
#echo "AMEND: $IS_AMEND"

#if ! [ -n "$IS_AMEND" ]; then

node ./src/git-version.js

git add ./src/assets/git-version.json
git commit --amend --no-verify

rev=git rev-parse --short HEAD

echo "[Commit-msg] Added git-version.json for $rev"

#fi
