name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: All things angular
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2
        with:
          # see the Configuration section for how you can create secrets
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          build_configuration: production
          base_href: /message-map/
          deploy_branch: gh-pages
          # The folder where your project is supposed to be after running ng build by the action.
          angular_dist_build_folder: dist/message-map
